### ISSUE TITLE
num_samples=0 error

### ISSUE THREAD

**Issue by kaka10018** [albumentations-team/autoalbument#16]
from e
hydra.errors.HydraException: Error calling 'torch.utils.data.DataLoader' : num_samples should be a positive integer value, but got num_samples=0
In my dataset class I am reading things inside a folder where I ran the search command is this the cause ?

**Comment by kaka10018** [comment]
i print the length of my image path list when dataset.py was instantiated i can see the length is 0
so how can I point working directory to the place where my images are located ?

**Comment by kaka10018** [comment]
fixed it just had to pass a parameter in root from yaml and then use it

**Comment by smpurkis** [comment]
Hi @ashish244co, I've encountered the same issue, but am unsure exactly how you fixed it, can you elaborate please? Thanks
