### ISSUE TITLE
missing parameter of input channels

### ISSUE THREAD

**Issue by huanghjA** [albumentations-team/autoalbument#19]
How to change the input channel into 1 as my dataset are not RGB images.

**Comment by Dipet** [comment]
Just simple use single channel image. But be careful, because some transforms works only with RGB images.

**Comment by huanghjA** [comment]
Thanks for your reply!
However, it seems that the input channel is set to 3 as default and I don't find a way to change it.

when I set my input image with shape (960, 1280, 3) as RGB, It can work without runtime error.
If I change the shape into (960, 1280, 1) as a gray image, the following error occur:
`ValueError: non-broadcastable output operand with shape (960,1280,1) doesn't match the broadcast shape (960,1280,3)`

**Comment by Dipet** [comment]
Describe what transforms you are using. Perhaps some of them do not support grayscale images, or maybe there is a bug in them.

**Comment by huanghjA** [comment]
In fact, this issue has been post in #8 .
In the file` search.yaml`, I delete all transforms but keep 
- _target_: autoalbument.faster_autoaugment.models.policy_operations.Rotate.
