### ISSUE TITLE
Which versions of the required libraries are needed to run?

### ISSUE THREAD

**Issue by IlyaLion** [albumentations-team/autoalbument#35]
Запускаю autoalbument в Google Colab. Устанавливаю свежую версию, запускаю пример
`!autoalbument-create --config-dir 'autoalbument' --task classification --num-classes 100`
`!autoalbument-search --config-dir 'autoalbument'`
Получаю ошибку 
`ImportError: cannot import name 'Batch' from 'torchtext.data' (/usr/local/lib/python3.7/dist-packages/torchtext/data/__init__.py)`
Обновляю pytorch-lightning, и ошибка уходит. Зато появляется новая:
`ImportError: cannot import name 'container_abcs' from 'torch._six' (/usr/local/lib/python3.7/dist-packages/torch/_six.py)`
Теперь обновляю timm, получаю другую ошибку:
`TypeError: Error instantiating 'autoalbument.faster_autoaugment.models.policy_operations.ShiftRGB' : __init__() missing 1 required positional argument: 'temperature'`
Обновляю hydra-core до версии 1.0.6. Появляется следующая ошибка:
`ValueError: Your 'LightningModule.training_step' signature contains an 'optimizer_idx' argument but in manual optimization optimizers must be handled by the user. Remove the optimizer_idx argument or set 'self.automatic_optimization = True'.`
Эту ошибку я уже не смог исправить, какие бы версии библиотек не устанавливал.
Какие же версии библиотек нужны, чтобы всё заработало?

**Comment by creafz** [comment]
Hi. I have created an example on Google Colab with pinned library versions - https://colab.research.google.com/drive/1ZdP23fDtjiq_nd6FA7oAyRp_jnRsttTC#scrollTo=gNe5VFlorntw

Could you please try to install the same versions and see whether it works for your case?

**Comment by IlyaLion** [comment]
It works! Thanks
