### ISSUE TITLE
Docker not run

### ISSUE THREAD

**Issue by Violonur-PavelBI** [albumentations-team/autoalbument#42]
Thank you so much for your work.
after starting the container according to the instructions, it gives an error about the absence of autoalbument-search
`:~/Desktop$ docker run -it --rm --gpus all --ipc=host -v /storage/3030/BuevichP/prj/autoalbument/examples/cifar10:/config -v /storage/3030/BuevichP/db/cifar10:/home/autoalbument/data --name FAA_Buevich_V3 -u $(id -u ${USER}):$(id -g ${USER}) ghcr.io/albumentations-team/autoalbument:latest`
/opt/autoalbument/entrypoint.sh: line 3: autoalbument-search: command not found

**Comment by Ulia-Demidova** [comment]
@Violonur-PavelBI I have the same problem. How did you solve it?

**Comment by Violonur-PavelBI** [comment]
I did all the stages of the dockerfile myself in the console on the  image pytorch/pytorch:1.7.1-cuda11.0-cudnn8-runtime and started by calling the script independently 30.11.2022, 22:58, "Ulia-Demidova" ***@***.***>***@***.*** I have the same problem. How did you solve it?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by tayden** [comment]
Did you ever find a way to get this working @Violonur-PavelBI?
